//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FavOrg.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FAVORG_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_FAVORGTYPE                  129
#define IDD_OPTIONS                     130
#define IDI_UNCHECKED                   131
#define IDI_CHECKMARK                   132
#define IDI_PAGEMOVED                   133
#define IDI_ICONQUESTION                138
#define IDI_ACCESSDENIED                139
#define IDI_PAGENONE                    140
#define IDI_SITENONE                    141
#define IDI_QUESTIONMARK                142
#define IDI_RESET                       143
#define IDI_TIMEOUT                     144
#define IDI_PAGEMOVED_UPDATED           145
#define IDD_LEGEND                      146
#define IDD_BYSTATE                     147
#define IDD_EDITURL                     149
#define IDI_FOLDERSEL                   158
#define IDI_FOLDER                      159
#define IDI_INPROCESS                   164
#define IDI_HOURGLASS                   165
#define IDC_MNU_QUESTION                501
#define IDC_MNU_CHECKED                 502
#define IDC_MNU_PAGENONE                503
#define IDC_MNU_MOVED                   504
#define IDC_MNU_SITENONE                505
#define IDC_MNU_TIMEOUT                 506
#define IDC_MNU_ACCESSDENIED            507
#define IDC_MNU_MOVED_UPDATED           508
#define IDC_MNU_UNCHECKED               509
#define IDC_MNU_RESET                   510
#define IDC_MNU_PICKICON                511
#define IDC_MNU_ASSIGNTHIS              512
#define IDC_REFRESH                     1000
#define IDC_FAVTREE                     1001
#define IDC_GO                          1002
#define IDC_CANCELACTION                1003
#define IDC_FINDFAVICONS                1005
#define IDC_ALLOWUPDATE                 1006
#define IDC_RESETTOROOT                 1007
#define IDC_PROGRESS                    1008
#define IDC_EDTIMEOUT                   1009
#define IDC_NOCONNECTIONTEST            1010
#define IDC_SELFOLDER                   1011
#define IDC_FAVNUMBER                   1012
#define IDC_CHECK_SITENONE              1013
#define IDC_CHECK_PAGENONE              1014
#define IDC_CHECK_TIMEOUT               1015
#define IDC_CHECK_ACCESSDENIED          1016
#define IDC_OPTIONGROUP                 1017
#define IDC_EDITURL                     1018
#define IDC_REFNAME                     1019
#define IDC_URLED                       1020
#define IDC_COUNT                       1021
#define IDC_SITENOTFOUND_COUNT          1022
#define IDC_PAGENOTFOUND_COUNT          1023
#define IDC_TIMEOUT_COUNT               1024
#define IDC_ACCESSDENIED_COUNT          1025
#define IDC_NOOVERWRITE                 1027
#define IDC_GENERATELOG                 32771
#define IDC_PICKICON                    32772
#define IDC_ASSIGNTHIS                  32773
#define IDC_CUSTOMICON                  32774
#define IDC_REMOVE                      32776
#define IDC_SHOWLEGEND                  32777
#define IDC_DELETEBYSTATE               32778
#define IDC_OPTIONS                     32779
#define IDC_FAVORGHELP                  32780
#define IDC_DISPINFO                    32785
#define IDC_ASSIGNCUST                  32786
#define IDC_EXPANDALL                   32787
#define IDC_COLLAPSEALL                 32788
#define IDC_EXPANDCURRENT               32789
#define IDC_COLLAPSECURRENT             32790
#define IDC_SELECTNONE                  32791
#define IDC_VIEWREPORT                  32792
#define IDS_FAVORITES                   61206
#define IDS_CLOSECONNECTION             61207
#define IDS_MSG_FROMFOLDER              61208
#define IDS_MSG_FAVNAME                 61209
#define IDS_MSG_ICONFOUND               61210
#define IDS_MSG_UPDATINGDEADLINK        61211
#define IDS_MSG_CHECKURL                61212
#define IDS_MSG_ACCESSDENIED            61213
#define IDS_MSG_TIMEOUT                 61214
#define IDS_MSG_NOSITE                  61215
#define IDS_MSG_UNKNOWN                 61216
#define IDS_MSG_OK                      61217
#define IDS_MSG_REDIRWITHUPDATE         61218
#define IDS_MSG_REDIR                   61219
#define IDS_MSG_NOTFOUND                61220
#define IDS_NUMFMT                      61221
#define IDS_DELETESELALERT              61222
#define IDS_ASSIGNSELALERT              61223
#define IDS_MSG_SELCOUNT                61224
#define IDS_MSG_LOGERROR                61225
#define IDS_STATUS_UNKNOWN              61226
#define IDS_STATUS_CHECKED              61227
#define IDS_STATUS_PAGENOTFOUND         61228
#define IDS_STATUS_PAGEMOVED            61229
#define IDS_STATUS_TIMEOUT              61230
#define IDS_STATUS_SITENOTFOUND         61231
#define IDS_STATUS_ACCESSDENIED         61232
#define IDS_STATUS_MOVEDUPDATED         61233
#define IDS_STATUS_UNCHECKED            61234
#define IDS_STATUS_RESET                61235
#define IDS_DELETEALLALERT              61237
#define IDS_NETWORKALERT                61238
#define IDS_RASALERTPROMPT              61239
#define IDS_RASALERTPROMPT2             61240

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
